### ISSUE TITLE
Publish package on npm

### ISSUE THREAD

**Issue by svens-uk** [Flarp/Distri-Node#17]
Since this is an node module, it'd be helpful if it were on npm. It'd increase visibility of the package, make it easier to find, and to install.

**Comment by ethan-dorta** [comment]
`npm install Flarp/Distri-Node`

?

**Comment by svens-uk** [comment]
But it's not registered on npm, meaning you don't get the visibility from that. And you'll just get the latest commit when installing/upgrading currently. Although that sounds great, you might get a breaking change when you upgrade, which is what npm is great at preventing.

Plus certain projects such as DefinitelyTyped greatly benefit when the package is published on npm as, in the case of DefinitelyTyped, it makes naming the typing files much easier, and avoids future conflicts.

**Comment by ethan-dorta** [comment]
I've tried syncing two repos, and it's really hard. If you think it can be done, by all means, lend a hand.

**Comment by svens-uk** [comment]
I wonder if [UMD](https://github.com/umdjs/umd) might be useful? I'll look into it.

**Comment by ethan-dorta** [comment]
UMD is a module standard, this is repos I'm talking about. NPM and Git both have separate repos, and you have to keep track of them both.

**Comment by svens-uk** [comment]
Sorry, I thought you meant keeping track of changes in both Distri-Node and Distri-JS, and hence were deprecating the former. Or I could just be forgetting how these modules fit together - it's been quite a while.

I'd be happy to keep track of Distri-Node and publish it to npm following semver, if you're okay with that too.

**Comment by ethan-dorta** [comment]
https://gist.github.com/fent/3140668

This looks like it will work.
