### ISSUE TITLE
Make Distri more modular

### ISSUE THREAD

**Issue by Flarp** [Flarp/Distri-Node#8]
As of now, Distri is really kind of a crazy mix of code, some of which doesn't even need to be there. One main thing I am thinking about removing is the `equalityPercentage` functionality, and in return, allow a user to define functions to check solutions themselves, with custom event emitters for a workgroup being completed, a workgroup being accepted, and a workgroup being rejected. This will probably be added before New Years, but I'm announcing it now because nobody is fucking reading this.

**Comment by Kurimizumi** [comment]
I'm reading it, and it sounds good! 

You could have built in functions which automatically check solutions, if the user wants to use them for convenience? For example, one which checks if all arguments passed to it are equal? It's late so I could probably explain this better at a later time.

Finally, I'll be working on that stats tracking module at some point soon, I'm having to rewrite JMTools for my school currently though.

**Comment by Flarp** [comment]
Yeah, equalityPercentage will be a built in function.

**Comment by Kurimizumi** [comment]
Awesome! I'll be sure to message you on Skype soon.

**Comment by Flarp** [comment]
19486482a08a872f1180b4b3fac05d29470d3765 might have done this, but unit tests are going to be added to make sure.
